### ISSUE TITLE
Declare project dependencies.

### ISSUE THREAD

**Issue by firminochangani** [Bcantz27/Mean-boilerplate#1]
To avoid erros when running the server.js file you should declare all project dependencies in package.json using --save option on install process. Eg: sudo npm i express-session --save
![terminal](https://cloud.githubusercontent.com/assets/1679333/10283558/fc557082-6b77-11e5-8131-e819e0707825.png)

**Comment by bryan27118** [comment]
Updated package.json and bower.json, just run npm install and bower install and all the dependencies will be added. I will be adding gulp to setup the project with one command.
